app/routes.py
from flask import Blueprint, render_template, redirect, url_for,jsonify
from flask import request
from .models import db, Persona, PersonaSesion,BibliotecaGeneralAnime,ListaAnime

import requests
import os
import hashlib

from bs4 import BeautifulSoup

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/formulario')
def formulario():
    return render_template('formulario.html')

@main.route('/iniciar_sesion')
def sesion():
    return render_template('iniciar_Sesion.html')

@main.route('/sesionRe')
def RegresarSession():
    return render_template('Sesion_abierta.html')

@main.route('/borrar_de_lista')
def eliminar_L():
    return render_template('borrar.html')

@main.route('/GuardadoM')
def GuardadManual():
    return render_template('guardado_manual.html')

@main.route('/submit_form', methods=['POST'])  ## Metodo para registrar a las personas
def submit_form():

    email = request.form.get('email')
    nickname = request.form.get('nickname')
    contrasena = request.form.get('contrasena')

    # Verificar si el nickname ya existe en la base de datos
    persona_existente = Persona.query.filter_by(email=email).first()

    if persona_existente:
        # El email ya está registrado, mostrar la página de ya_registrado
        return render_template('ya_existe.html')

    else:
        # El nickname no está registrado, agregar la nueva persona a la base de datos
        # Generar salt
        salt = os.urandom(16)
        # Hash de la contraseña con el salt
        contrasena_salted = contrasena.encode('utf-8') + salt
        contrasena_hash = hashlib.pbkdf2_hmac('sha256', contrasena_salted, salt, 100000).hex()

        nueva_persona = Persona(email=email, nickname=nickname, contrasena=contrasena_hash)
        db.session.add(nueva_persona)
        db.session.commit()

        sesion_nueva_persona = PersonaSesion(user_id=nueva_persona.id, contrasena_hash=contrasena_hash, salt=salt)
        db.session.add(sesion_nueva_persona)
        db.session.commit()

        # Redirigir a la página de éxito
        return redirect(url_for('main.exito'))


@main.route('/ver_registros')
def ver_registros():
    personas = Persona.query.all()
    return render_template('ver_registros.html', personas=personas)

@main.route('/exito')
def exito():
    return render_template('exito.html')


@main.route('/Sesion_on', methods=['POST'])
def Sesion_On():
    email = request.form.get('email')
    contrasena = request.form.get('contrasena')

    # Verificar si el email existe en la base de datos
    persona_existente = Persona.query.filter_by(email=email).first()

    if persona_existente:
        # Persona encontrada, obtener su id
        user_id = persona_existente.id

        # Buscar la instancia de PersonaSesion basándote en el user_id
        sesion_persona_existente = PersonaSesion.query.filter_by(user_id=user_id).first()

        if sesion_persona_existente:
            # Contraseña almacenada y salt de la PersonaSesion
            contrasena_hash = sesion_persona_existente.contrasena_hash
            salt = sesion_persona_existente.salt

            # Verificar la contraseña ingresada con la almacenada
            contrasena_salted = contrasena.encode('utf-8') + salt
            contrasena_ingresada_hash = hashlib.pbkdf2_hmac('sha256', contrasena_salted, salt, 100000).hex()

            if contrasena_ingresada_hash == contrasena_hash:
                # Contraseña correcta, redirigir a la página de éxito
                return render_template('Sesion_abierta.html')
            else:
                # Contraseña incorrecta, manejar esto como desees
                return render_template('ya_existe.html')
        else:
            # No se encontró una instancia de PersonaSesion para el usuario
            return render_template('ya_existe.html')

    else:
        # Persona no encontrada, manejar como desees
        return render_template('ya_existe.html')

@main.route('/BuscarAnime')
def BA():
    return render_template('BuscarAnime.html')

####################################################
@main.route('/scrap_anime_data', methods=['GET'])
def scrap_anime_data():
    url_base = 'https://myanimelist.net/anime.php?letter={}'
    abecedario = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    max_paginas = 1

    for letra in abecedario:
        for pagina_actual in range(1, max_paginas + 1):
            url = f'{url_base.format(letra)}&show={(pagina_actual - 1) * 50}'
            response = requests.get(url)
            html = response.text
            soup = BeautifulSoup(html, 'html.parser')

            tabla = soup.select_one('#content > div.js-categories-seasonal.js-block-list.list')

            if tabla:
                datos_animes = []

                for fila in tabla.find_all('tr'):
                    celdas = fila.find_all('td')

                    if len(celdas) >= 2:
                        nombre_bruto = celdas[1].get_text(strip=True)
                        nombre_sin_add = nombre_bruto.split('add')[0].strip()
                        episodios = celdas[3].get_text(strip=True)

                        # Verificar si el anime ya existe en la base de datos
                        if not BibliotecaGeneralAnime.query.filter_by(nombre=nombre_sin_add).first():
                            # Si no existe, agregar el nuevo anime
                            nuevo_anime = BibliotecaGeneralAnime(nombre=nombre_sin_add, capitulos=episodios)
                            db.session.add(nuevo_anime)
                            db.session.commit()

                            print(f'Nuevo anime agregado: {nombre_sin_add} - Capítulos: {episodios}')

                print(f'Datos guardados en "resultados_anime_{letra}_pagina_{pagina_actual}.txt"')

            else:
                print(f'No se encontró la tabla en la página {letra}, {pagina_actual}. Fin del scraping.')
                break

    return jsonify({'message': 'Web scraping completado'})


def parse_anime_info(anime_info):
    parts = anime_info.split('\t')
    nombre_anime = parts[0].split(': ')[1]
    capitulos_anime = parts[1].split(': ')[1]

    return nombre_anime, capitulos_anime


@main.route('/resultados_busqueda', methods=['POST'])
def resultados_busqueda():
    search_query = request.form.get('searchQuery')

    # Realizar la búsqueda en la base de datos
    resultados = BibliotecaGeneralAnime.query.filter(BibliotecaGeneralAnime.nombre.ilike(f'%{search_query}%')).all()

    # Excluir la primera instancia de la búsqueda
    resultados_sin_primera_instancia = resultados[1:]

    resultados_json = [{'nombre': anime.nombre, 'capitulos': anime.capitulos} for anime in resultados_sin_primera_instancia]

    return jsonify(resultados_json)

# ... (código anterior)

@main.route('/registrar_anime_m', methods=['POST'])
def registro_manual():
    nombre_anime = request.form.get('nombre')
    capitulos_anime = request.form.get('capitulos')
    id_persona = request.form.get('id')

    # Verificar si el anime ya existe en la base de datos
    if not ListaAnime.query.filter_by(nombre=nombre_anime).first():
        # Si no existe, agregar el nuevo anime
        nuevo_anime = ListaAnime(nombre=nombre_anime, capitulos=capitulos_anime, persona_id=id_persona, biblioteca_id=id_persona)
        db.session.add(nuevo_anime)
        db.session.commit()

        return render_template('exito_manual.html', nombre_anime=nombre_anime, capitulos_anime=capitulos_anime)
    else:
        # El anime ya existe, manejar esto como desees
        return render_template('error.html', nombre_anime=nombre_anime)
    
@main.route('/eliminar_anime_m', methods=['POST'])
def eliminar_manual():
    nombre_anime = request.form.get('nombre')
    id_persona = request.form.get('id')

    # Buscar el anime en la base de datos
    anime_a_eliminar = ListaAnime.query.filter_by(nombre=nombre_anime, persona_id=id_persona).first()

    if anime_a_eliminar:
        # Si existe, eliminar el anime
        db.session.delete(anime_a_eliminar)
        db.session.commit()

        return render_template('exito_manual.html', operacion='eliminado', nombre_anime=nombre_anime)
    else:
        # El anime no existe, manejar esto como desees
        return render_template('error.html', operacion='eliminar', nombre_anime=nombre_anime)



    
@main.route('/ver_lista_anime', methods=['GET'])
def ver_lista_anime():
    # Obtener el ID del parámetro de la solicitud
    persona_id = request.args.get('persona_id')

    # Filtrar la lista de animes por el ID de la persona
    animes = ListaAnime.query.filter_by(persona_id=persona_id).all()

    # Crear una lista con los datos filtrados
    anime_list = [{'nombre': anime.nombre, 'capitulos': anime.capitulos} for anime in animes]

    return jsonify(anime_list)

app/templates/BuscarAnime.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Búsqueda</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            background-color: #f8f8f8;
            color: #333;
            position: relative;
        }

        h1 {
            text-align: center;
            color: #008080;
        }

        #searchForm {
            margin: 20px auto;
            text-align: center;
        }

        label {
            font-size: 18px;
            margin-right: 10px;
        }

        #searchQuery {
            font-size: 16px;
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }

        #results {
            margin-top: 20px;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            font-size: 16px;
            margin-bottom: 8px;
            background-color: #fff;
            padding: 12px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        #progressBar {
            width: 100%;
            background-color: #ddd;
            height: 20px;
            margin-top: 10px;
            border-radius: 4px;
            overflow: hidden;
            display: none;
            transition: height 0.3s ease, opacity 0.3s ease;
        }

        #progress {
            height: 100%;
            width: 0%;
            background-color: #4caf50;
            border-radius: 4px;
            transition: width 0.3s ease;
        }

        .button-container {
            text-align: center;
            margin-top: 10px;
        }

        .button-container button {
            font-size: 16px;
            padding: 8px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-left: 10px;
        }

        #buscarButton {
            background-color: #008080;
            color: #fff;
        }

        #buscarButton:hover {
            background-color: #005555;
        }

        #actualizarButton {
            background-color: #4caf50;
            color: #fff;
        }

        #actualizarButton:hover {
            background-color: #388e3c;
        }

        #addToListButton {
            font-size: 12px;
            padding: 8px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #2196F3;
            color: #fff;
            margin-left: 10px;
        }

        #addToListButton:hover {
            background-color: #0b7dda;
        }

        #guardadoManualButton {
            font-size: 18px;
            padding: 8px;
            border: 50px;
            border-radius: 4px;
            cursor: pointer;
            background-color: #FFD700;
            color: #333;
            margin-left: 10px;
        }

        #guardadoManualButton:hover {
            background-color: #FFC700;
        }

        #regresarButton {
            font-size: 16px;
            padding: 8px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #d1bc42;
            color: #333;
            margin-left: 10px;
        }

        #regresarButton:hover {
            background-color: #a3914e;
        }

        #resultCount {
            font-size: 14px;
            color: #888;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <h1>Búsqueda</h1>

    <div class="button-container">
        <a href="{{ url_for('main.RegresarSession') }}"  class="boton" id="regresarButton" >Regresar</a>
    </div>


    <div class="button-container">
        <a href="{{ url_for('main.GuardadManual') }}"  class="boton" id="guardadoManualButton" >Guardado Manual</a>
    </div>

    
    <div id="searchForm">
        <label for="searchQuery">Buscar Anime:</label>
        <input type="text" id="searchQuery" name="searchQuery" placeholder="Ingrese su búsqueda" required oninput="performSearch()">
        <span id="resultCount"></span>
    </div>

    <div id="progressBar">
        <div id="progress"></div>
    </div>

    <div id="results">
        <ul id="animeList"></ul>
    </div>

    <div class="button-container">
        <button id="actualizarButton" onclick="performUpdate()">Actualizar</button>
    </div>

    <script>
        function handleResults(responseText) {
            var resultsContainer = document.getElementById('animeList');
            var resultCountElement = document.getElementById('resultCount');
            resultsContainer.innerHTML = '';

            var resultados = JSON.parse(responseText);
            resultCountElement.textContent = `Coincidencias encontradas: ${resultados.length}`;

            resultados.forEach(function (resultado) {
                var listItem = document.createElement('li');
                listItem.textContent = resultado.nombre + ' - Capítulos: ' + resultado.capitulos;

                // Agregar botón para agregar a la lista
                var addButton = document.createElement('button');
                addButton.textContent = 'Agregar a mi lista';
                addButton.onclick = function() {
                    // Lógica para agregar el anime a la lista (puedes implementar esto)
                    addToAnimeList(resultado);
                };

                listItem.appendChild(addButton);
                resultsContainer.appendChild(listItem);
            });

            // Ocultar la barra de progreso después de cargar los archivos
            document.getElementById('progressBar').style.display = 'none';
        }

        function performSearch() {
            var searchQuery = document.getElementById('searchQuery').value;
            document.getElementById('progressBar').style.display = 'block';

            var xhr = new XMLHttpRequest();
            xhr.open('POST', '/resultados_busqueda', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    handleResults(xhr.responseText);
                }
            };

            xhr.send('searchQuery=' + searchQuery);
        }

        function performUpdate() {
            var progressBar = document.getElementById('progressBar');
            progressBar.style.display = 'block';
            document.getElementById('progress').style.width = '0%';

            var xhr = new XMLHttpRequest();
            xhr.open('GET', '/scrap_anime_data', true);
            xhr.setRequestHeader('Content-Type', 'application/json');
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    performSearch();
                }
            };

            xhr.onprogress = function (event) {
                if (event.lengthComputable) {
                    var percentComplete = (event.loaded / event.total) * 100;
                    document.getElementById('progress').style.width = percentComplete + '%';
                }
            };

            xhr.onloadend = function () {
                progressBar.style.display = 'none';
            };

            xhr.send();
        }
    </script>
</body>
</html>

app/templates/Sesion_abierta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de animes</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            text-align: center;
            color: #333;
        }

        h1 {
            color: #0066cc;
        }

        #menu {
            background-color: #0066cc;
            padding: 10px;
            margin-top: 20px;
            border-radius: 5px;
            display: inline-block;
        }

        .boton {
            display: inline-block;
            background-color: #ffffff;
            color: #0066cc;
            padding: 8px 12px;
            margin: 0 5px;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .boton:hover {
            background-color: #0066cc;
            color: #ffffff;
        }

        label {
            color: #ffffff;
            margin-right: 10px;
        }

        #animeList {
            background-color: #ffffff;
            padding: 20px;
            margin-top: 20px;
            border-radius: 5px;
            display: none;
        }

        #animeItems {
            list-style-type: none;
            padding: 0;
        }

        #animeItems li {
            margin-bottom: 10px;
        }

        #personaIdTexto {
            color: #333;
            margin-top: 10px;
        }
    </style>
</head>
<body>


    <h1>Bienvenido Usuario</h1>

    <div id="menu">
        <button id="verListaBtn" class="boton">Ver Lista</button>
        <a href="{{ url_for('main.BA') }}" class="boton">Agregar Anime</a>
        <a href="{{ url_for('main.eliminar_L') }}" class="boton">Eliminar Anime</a>
        <a href="{{ url_for('main.index') }}" class="boton">Salir Sesión</a>
        <!-- Movemos la caja de entrada del ID de Persona debajo de los botones -->
        <label for="personaId">ID de Persona para ver lista:</label>
        <input type="text" id="personaId" required>
    </div>

    <div id="animeList">
        <h2>Lista de Animes</h2>
        <ul id="animeItems">
            <!-- Los animes se mostrarán aquí dinámicamente -->
        </ul>
        <!-- Movemos el elemento del ID de Persona debajo de la lista de animes -->
        <p id="personaIdTexto"></p>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        // Función para cargar la lista de animes
        function cargarListaAnime(personaId) {
            // Hacer una solicitud AJAX para obtener la lista de animes con el ID de la persona
            $.get("{{ url_for('main.ver_lista_anime') }}?persona_id=" + personaId, function(data) {
                // Limpiar la lista actual
                $("#animeItems").empty();

                // Iterar sobre los datos recibidos y agregar cada anime a la lista
                data.forEach(function(anime) {
                    $("#animeItems").append("<li>" + "Anime: " + anime.nombre + " - Capítulos: " + anime.capitulos + "</li>");
                });

                // Mostrar el ID de la persona antes de la lista
                $("#personaIdTexto").text("ID de Persona: " + personaId);

                // Mostrar la lista después de cargarla
                $("#animeList").show();
            });
        }

        // Asociar la función de carga de lista al evento click del botón "Ver Lista"
        $("#verListaBtn").click(function() {
            // Obtener el ID de la persona desde el input
            var personaId = $("#personaId").val();

            // Verificar que se haya ingresado un ID antes de cargar la lista
            if (personaId) {
                cargarListaAnime(personaId);
            } else {
                alert("Por favor, ingresa un ID de persona antes de ver la lista.");
            }
        });
    </script>
    <div id="background-gif" style="height: 30vh; margin: 5;">
        <img src="https://i.pinimg.com/originals/ff/16/e5/ff16e5d60e3ea8d28682e89b5baf5510.gif" alt="Background Gif" style="width: 40%; max-height: 200%;">
    </div>
</body>
</html>

app/templates/borrar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registro de Usuario</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">
</head>
<body>
    <header>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTITwcgA9qGQAZcXdslSgxsEkn_iRPgMq5h1w&usqp=CAU" alt="Imagen de Encabezado" style="width: 100%; max-height: 200px; border-radius: 8px 8px 0 0;">
        <h1>Guardado Manual</h1>
    </header>
    <main>
        <form action="{{ url_for('main.eliminar_manual') }}" method="post" class="registro_manual">
            <label for="nombre">Nombre de anime:</label>
            <input type="nombre" id="nombre" name="nombre" required>
            <label for="id">Id personal:</label>
            <input type="text" id="id" name="id" required>
            <button type="submit" class="boton">Eliminar</button>
        </form>
        <a href="{{ url_for('main.RegresarSession') }}"  class="boton" id="regresarButton" >Regresar</a>
    </main>
    <footer>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </footer>
</body>
</html>

app/templates/error.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de animes</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/estilos.css') }}">
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh; /* Ajusta la altura a la altura de la ventana */
            margin: 0; /* Elimina el margen predeterminado del body */
        }

        h1 {
            text-align: center;
        }

        .boton {
            display: inline-block;
            margin: 10px;
            padding: 10px 15px;
            background-color: #0275d8;
            color: white;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }

        .boton:hover {
            background-color: #025aa5;
        }

        .botones-container {
            display: flex;
            justify-content: center;
        }

        .gif-container {
            margin-bottom: 20px; /* Ajusta el margen inferior del contenedor del gif */
        }
    </style>
</head>
<body>
    <div class="gif-container">
        <img src="https://i.pinimg.com/originals/56/7f/00/567f0061446aa28a94721679278bec24.gif" alt="GIF">
    </div>
    <h1>Error, ya existe o esta mal</h1>
    <div class="botones-container">
        <div class="button-container">
            <a href="{{ url_for('main.RegresarSession') }}"  class="boton" id="regresarButton" >Regresar</a>
        </div>
    </div>
</body>
</html>

app/templates/exito.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de animes</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/estilos.css') }}">
</head>
<body>
    <h1>Datos guardados exitosamente</h1>
    <a href="{{ url_for('main.sesion') }}" class="boton">Iniciar Sesion</a>
</body>
</html>

app/templates/formulario.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registro de Usuario</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">
</head>
<body>
    <header>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTITwcgA9qGQAZcXdslSgxsEkn_iRPgMq5h1w&usqp=CAU" alt="Imagen de Encabezado" style="width: 100%; max-height: 200px; border-radius: 8px 8px 0 0;">
        <h1>Registro de Usuario</h1>
    </header>
    <main>
        <form action="{{ url_for('main.submit_form') }}" method="post" class="formulario">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            <label for="nickname">Nickname:</label>
            <input type="text" id="nickname" name="nickname" required>
            <label for="nombre">Contraseña:</label>
            <input type="text" id="contrasena" name="contrasena" required>
            <button type="submit" class="boton">Registrarse</button>
        </form>
        <a href="{{ url_for('main.index') }}" class="boton">Inicio</a>
    </main>
    <footer>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </footer>
</body>
</html>

app/templates/guardado_manual.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registro de Usuario</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">
</head>
<body>
    <header>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTITwcgA9qGQAZcXdslSgxsEkn_iRPgMq5h1w&usqp=CAU" alt="Imagen de Encabezado" style="width: 100%; max-height: 200px; border-radius: 8px 8px 0 0;">
        <h1>Guardado Manual</h1>
    </header>
    <main>
        <form action="{{ url_for('main.registro_manual') }}" method="post" class="registro_manual">
            <label for="nombre">Nombre de anime:</label>
            <input type="nombre" id="nombre" name="nombre" required>
            <label for="capitulos">Numero de Capitulos:</label>
            <input type="text" id="capitulos" name="capitulos" required>
            <label for="id">Id personal:</label>
            <input type="text" id="id" name="id" required>
            <button type="submit" class="boton">Registrarse</button>
        </form>
        <a href="{{ url_for('main.RegresarSession') }}"  class="boton" id="regresarButton" >Regresar</a>
    </main>
    <footer>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </footer>
</body>
</html>

app/templates/iniciar_Sesion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registro de Usuario</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">
</head>
<body>
    <header>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTITwcgA9qGQAZcXdslSgxsEkn_iRPgMq5h1w&usqp=CAU" alt="Imagen de Encabezado" style="width: 100%; max-height: 200px; border-radius: 8px 8px 0 0;">
        <h1>Iniciar sesion</h1>
    </header>
    <main>
        <form action="{{ url_for('main.Sesion_On') }}" method="post" class="iniciar_sesion">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            <label for="contrasena">Contraseña:</label>
            <input type="text" id="contrasena" name="contrasena" required>
            <button type="submit" class="boton">Iniciar </button>
        </form>
        <a href="{{ url_for('main.index') }}" class="boton">Inicio</a>
    </main>
    <footer>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </footer>
</body>
</html>

app/templates/ver_registros.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista Anime/Manga</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/estilos.css') }}">
</head>
<body>
    <h1>Registros Guardados:</h1>
    <ul>
        <!-- Jinja2 -->
        {% for persona in personas %}
        <li>{{persona.email}} -  {{persona.contrasena}} - {{persona.nickname}}</li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('main.index') }}" class="boton" >Inicio</a>
</body>
</html>

app/templates/ya_existe.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de animes</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/estilos.css') }}">
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh; /* Ajusta la altura a la altura de la ventana */
            margin: 0; /* Elimina el margen predeterminado del body */
        }

        h1 {
            text-align: center;
        }

        .boton {
            display: inline-block;
            margin: 10px;
            padding: 10px 15px;
            background-color: #0275d8;
            color: white;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }

        .boton:hover {
            background-color: #025aa5;
        }

        .botones-container {
            display: flex;
            justify-content: center;
        }

        .gif-container {
            margin-bottom: 20px; /* Ajusta el margen inferior del contenedor del gif */
        }
    </style>
</head>
<body>
    <div class="gif-container">
        <img src="https://i.pinimg.com/originals/56/7f/00/567f0061446aa28a94721679278bec24.gif" alt="GIF">
    </div>
    <h1>Error, Correo ya existente o contraseña mal</h1>
    <div class="botones-container">
        <a href="{{ url_for('main.ver_registros') }}" class="boton">Ver Registros</a>
        <a href="{{ url_for('main.index') }}" class="boton">Inicio</a>
        <a href="{{ url_for('main.formulario') }}" class="boton">Registrarse</a>
    </div>
</body>
</html>